"""add doctors, services, variants, appointments, offers, exchange rates, admin users

Revision ID: 11885cf1fe5b
Revises: 03fd616f1683
Create Date: 2026-08-13 12:35:38.635483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11885cf1fe5b'
down_revision = '03fd616f1683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('specialty_ar', sa.String(length=100), nullable=True),
    sa.Column('specialty_en', sa.String(length=100), nullable=True),
    sa.Column('bio_ar', sa.Text(), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.String(length=150), nullable=False),
    sa.Column('title_en', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('duration_estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_services',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'service_id')
    )
    op.create_table('service_concerns',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('concern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concern_id'], ['concerns.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'concern_id')
    )
    op.create_table('service_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('brand_name_ar', sa.String(length=100), nullable=False),
    sa.Column('brand_name_en', sa.String(length=100), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('service_variant_id', sa.Integer(), nullable=False),
    sa.Column('offer_price_syp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['service_variant_id'], ['service_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('service_variant_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('preferred_day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_datetime', sa.DateTime(), nullable=True),
    sa.Column('reminder_call_status', sa.String(length=20), nullable=True),
    sa.Column('reminder_call_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('followup_sent', sa.Boolean(), nullable=True),
    sa.Column('followup_sent_at', sa.DateTime(), nullable=True),
    sa.Column('offer_item_id', sa.Integer(), nullable=True),
    sa.Column('final_price_syp_at_booking', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['offer_item_id'], ['offer_items.id'], ),
    sa.ForeignKeyConstraint(['service_variant_id'], ['service_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('offer_items')
    op.drop_table('service_variants')
    op.drop_table('service_concerns')
    op.drop_table('doctor_services')
    op.drop_table('services')
    op.drop_table('offers')
    op.drop_table('exchange_rates')
    op.drop_table('doctors')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
