"""add is_available to doctors

Revision ID: 4eb4bfec8bbc
Revises: eb33c0eb0e21
Create Date: 2026-08-31 22:27:43.123850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb4bfec8bbc'
down_revision = 'eb33c0eb0e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.alter_column('is_available', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
