"""add is_available to services

Revision ID: eb33c0eb0e21
Revises: 11885cf1fe5b
Create Date: 2026-08-31 21:10:01.245512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb33c0eb0e21'
down_revision = '11885cf1fe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.alter_column('is_available', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
